.section .text

/* divide by zero */
INT_0x00:

/* debug exception */
INT_0x01:

/* NMI interrupt */
INT_0x02:

/* breakpoint */
INT_0x03:

/* overflow */
INT_0x04:

/* BOUND range exceeded */
INT_0x05:

/* invalid opcode */
INT_0x06:

/* math coprocessor not available */
INT_0x07:

/* double fault */
INT_0x08:

/* coprocessor segment overrun */
INT_0x09:

/* invalid TSS */
INT_0x0A:

/* segment not present */
INT_0x0B:

/* stack segment fault */
INT_0x0C:

/* general protection */
INT_0x0D:

/* page fault */
INT_0x0E:

/* x87 FPU error */
INT_0x10:

/* alignment check */
INT_0x11:

/* machine check */
INT_0x12:

/* SIMD floating point exception */
INT_0x13:

/* virtualization exception */
INT_0x14:

/* control protection exception */
INT_0x15:
