/*
 * trunix init system
 * Copyright (C) 2026  spenna
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

.text
path:
	.asciz "/bin/test"

.globl _start
_start:
	movl $2, %eax
	int $0x80
	testl %eax, %eax
	js 3f
	jz 2f

1: /* parent */
	jmp 1b

2: /* child */
	movl $8, %eax
	movl $path, %ebx
	movl $0, %ecx
	movl $0, %edx
	int $0x80
0:
	jmp 0b

3: /* fork failed */
	jmp 3b
